apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    #argocd.argoproj.io/hook: PostSync
  labels:
    version: "6"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: docker.io/library/bash:5
          command: ["bash"]        # example command simulating a bug which triggers the FailJob action
          args:
            - -c
            - echo "Hello postSync!" && exit 1
