apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: docker.io/library/bash:5
          command: ["bash"]        # example command simulating a bug which triggers the FailJob action
          args:
            - -c
            - echo "Hello preSync!" exit 1
